### ISSUE TITLE
A friend's name has padding from the regular name, having it look messy

### ISSUE THREAD

**Issue by BloodDragooner** [Oocrop/local-nicknames#1]
Hello, the script is working as intended, but I encountered a small bug: When you change a friend's name whose username has spaces in it, it doesn't look quite right. 
![Ends up looking like this](https://user-images.githubusercontent.com/33168706/89829844-7bbe7980-db18-11ea-8e8d-d058a6aa64ee.png)

Hope this is helpful, thanks for the cool script :)

**Comment by Oocrop** [comment]
You can hover over nickname to see original one, that's why it has that padding
