### ISSUE TITLE
"Well, this is awkward" crash upon entering certain servers

### ISSUE THREAD

**Issue by sapphonie** [Oocrop/local-nicknames#3]
No idea of root cause, but this plugin causes crashes when entering certain servers, which are then only fixable by uninstalling the plugin or powercord.

**Comment by deftkHD** [comment]
Also applies for certain DMs

**Comment by Oocrop** [comment]
Sorry I didn't reply earlier, I don't check github often
The crash was caused by moving to a new injection method for nicknames in chat and it was conflicting with reply injection
I noticed it and removed reply injection, but forgot to push the fix
Should be fine now
